package com.iaaa.dto;

import javax.persistence.*;

/**
 * Created by jackalhan on 3/22/16.
 */

public class Vehicle {

    // An autogenerated id (unique for each user in the db)

    private String vehicleName;
    private String year;
    private String direction;
    private String hwy;

    @Override
    public String toString() {
        return "Vehicle{" +
                "vehicleName='" + vehicleName + '\'' +
                ", year=" + year +
                ", direction='" + direction + '\'' +
                ", hwy='" + hwy + '\'' +
                '}';
    }

    public String getVehicleName() {
        return vehicleName;
    }

    public void setVehicleName(String vehicleName) {
        this.vehicleName = vehicleName;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getDirection() {
        return direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    public String getHwy() {
        return hwy;
    }

    public void setHwy(String hwy) {
        this.hwy = hwy;
    }

    public Vehicle() {
    }

    public Vehicle(String vehicleName, String year, String direction, String hwy) {
        this.vehicleName = vehicleName;
        this.year = year;
        this.direction = direction;
        this.hwy = hwy;
    }


}
